services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql_db"
    environment:
      - SA_PASSWORD=ChangeThis!!1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: ./src
      dockerfile: Medicines.API/Dockerfile
    container_name: medicines_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Server=mssql_db,1433;Database=MedicinesDB;User=sa;Password=ChangeThis!!1;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5010:80"
    depends_on:
      - mssql

volumes:
  mssql_data:

#docker-compose -p medicines down ; docker-compose -p medicines up --build -d